spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/oscoder?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456abcd
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: shenyang613@163.com
    #授权码
    password: NNKJXXRPAOGGLTMP
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#mybatis配置
mybatis:
  typeAliasesPackage: com.oscoder.amazon.helper.user.service.data.po,com.oscoder.amazon.helper.user.service.security.encrypt
  mapperLocations: classpath*:mapper/*.xml
  type-handlers-package: com.oscoder.amazon.helper.user.service.security.encrypt